#!/bin/bash
#######################################################################
#
#
#
#
#
#
#
#
#
#######################################################################


ppas:
  - ppa:libreoffice/ppa
  - ppa:saiarcot895/myppa
  - ppa:git-core/ppa
  - ppa:webupd8team/tor-browser
  - ppa:webupd8team/terminix
  - ppa:maarten-baert/simplescreenrecorder
  - ppa:shutter/ppa
  - chrome: 
      url: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      sfile: /etc/apt/sources.list.d/google.list
      key: https://dl-ssl.google.com/linux/linux_signing_key.pub
