#!/bin/bash
#######################################################################
#
#
#
#
#
#
#
#
#
#######################################################################


# NOTE: This file is very whitespace angry,
#       in future need whitespace friendly
ppas:
  - ppa:libreoffice/ppa
  - ppa:saiarcot895/myppa
  - ppa:git-core/ppa
  - ppa:webupd8team/tor-browser
  - ppa:webupd8team/terminix
  - ppa:mhsabbagh/greenproject
  - ppa:maarten-baert/simplescreenrecorder
  - ppa:shutter/ppa
  - chrome: 
  - filebeats: 
  chrome:
    - url: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - sfile: /etc/apt/sources.list.d/google.list
    - key: https://dl-ssl.google.com/linux/linux_signing_key.pub
  filebeats: 
    - url: deb https://packages.elastic.co/beats/apt stable main
    - sfile: /etc/apt/sources.list.d/beats.list
    - key: https://packages.elastic.co/GPG-KEY-elasticsearch


logstash:
   server: 10.0.2.5

freeipa:
   ip:       10.0.2.5
   hostname: ipa
   fqdn:     ipa.example.com
   
